# Generated by Django 5.2.8 on 2025-12-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_registration_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='priority',
        ),
        migrations.AddField(
            model_name='registration',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.priority'),
        ),
    ]
