# Generated by Django 5.2.8 on 2025-11-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_foodreservation_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodreservation',
            name='meal_type',
            field=models.CharField(choices=[('all', 'همه وعده ها'), ('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام')], default='all', max_length=20),
        ),
    ]
