# Generated by Django 5.2.8 on 2025-12-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_foodreservation_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='national_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('participant', 'course')},
        ),
    ]
