# Generated by Django 5.2.8 on 2025-12-04 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_participant_priority_registration_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.participant')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.registration')),
            ],
            options={
                'unique_together': {('participant', 'registration')},
            },
        ),
    ]
