# Generated by Django 5.2.8 on 2025-12-03 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_participant_national_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodreservation',
            name='registration',
        ),
        migrations.AddField(
            model_name='foodreservation',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_reservations', to='event.participant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='relation',
            field=models.CharField(choices=[('self', 'خودم'), ('spouse', 'همسر'), ('child', 'فرزند'), ('guest', 'مهمان')], max_length=20),
        ),
    ]
