# Generated by Django 5.2.8 on 2025-12-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_registeredparticipant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='participant',
        ),
    ]
