# Generated by Django 5.2.8 on 2025-12-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_registration_user_alter_participant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
