# Generated by Django 5.2.8 on 2025-12-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_participant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
