# Generated by Django 5.2.8 on 2025-12-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_participant_is_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_reserved',
        ),
    ]
