# Generated by Django 5.2.8 on 2025-12-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_participant_is_reserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredparticipant',
            old_name='is_confirmed',
            new_name='is_reserved',
        ),
    ]
