# Generated by Django 5.2.8 on 2025-12-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_rename_is_confirmed_registeredparticipant_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
