# Generated by Django 5.2.8 on 2025-12-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_participant_is_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=9, null=True, unique=True),
        ),
    ]
