# Generated by Django 5.2.8 on 2025-12-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_registration_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=9, null=True, unique=True),
        ),
    ]
