# Generated by Django 5.2.8 on 2025-12-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_registration_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('relation', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'درخواست تحت بررسی'), ('accepted', 'درخواست قبول شده'), ('rejected', ' درخواست مردود شده'), ('canceled', ' درخواست منصرف شده ')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='registeredparticipant',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.guest'),
        ),
    ]
