# Generated by Django 5.2.8 on 2025-12-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_guest_alter_registration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='relation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
