# Generated by Django 5.2.8 on 2025-12-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_guest_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredparticipant',
            name='guest',
        ),
        migrations.AddField(
            model_name='guest',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='event.registration'),
            preserve_default=False,
        ),
    ]
