# Generated by Django 5.2.8 on 2025-12-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_registeredparticipant_guest_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(fields=('national_id', 'registration'), name='unique_national_event'),
        ),
    ]
