# Generated by Django 5.2.8 on 2025-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_guest_unique_national_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_guests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
