# Generated by Django 5.2.8 on 2025-12-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_event_max_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='capacity',
        ),
        migrations.AddField(
            model_name='course',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_reserved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='relation',
            field=models.CharField(choices=[('self', 'خودم'), ('spouse', 'همسر'), ('child', 'فرزند'), ('father', 'پدر'), ('mother', 'مادر')], max_length=20),
        ),
    ]
