# Generated by Django 5.2.8 on 2025-12-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_remove_course_capacity_course_max_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'درخواست تحت بررسی'), ('accepted', 'درخواست قبول شده'), ('rejected', ' مردودی از طرف ادمین'), ('canceled', '  انصراف از طرف کاربر')], default='pending', max_length=20),
        ),
    ]
