# Generated by Django 5.2.8 on 2025-12-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_registeredparticipant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
