# Generated by Django 5.2.8 on 2025-12-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_guest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_guests_per_user',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('accepted', 'قبول'), ('rejected', 'مردود')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registeredparticipant',
            name='status',
            field=models.CharField(choices=[('pending', 'در حال بررسی'), ('accepted', 'قبول'), ('rejected', 'مردود')], default='pending', max_length=20),
        ),
    ]
