# Generated by Django 5.2.8 on 2025-12-25 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_event_max_guests_per_user_alter_guest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='national_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='event.registration'),
        ),
    ]
