# Generated by Django 5.2.8 on 2025-12-25 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_alter_guest_national_id_alter_guest_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='event.registration'),
        ),
    ]
