# Generated by Django 5.2.8 on 2025-12-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_alter_guest_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
