# Generated by Django 5.2.8 on 2025-12-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
