# Generated by Django 5.2.8 on 2025-12-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_course_is_publish_event_is_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='registration_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_start',
            field=models.DateField(),
        ),
    ]
